# Generated by Django 2.2.10 on 2020-04-10 15:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Holliday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('slug', models.SlugField(max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('page_number', models.PositiveIntegerField(default=0)),
                ('content', models.CharField(blank=True, max_length=50000)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('slug', models.SlugField(max_length=100, null=True, unique=True)),
                ('holliday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='holiday.Holliday')),
                ('parent_room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='holiday.Room')),
            ],
        ),
    ]
